### ISSUE TITLE
Vagrant1.7.4でPuppet4によるプロビジョニングが実行できない

### ISSUE THREAD

**Issue by mk2** [mk2/Memorandom#2]
```
==> default: Running Puppet with site.pp...
==> default: Error: Could not parse application options: invalid option: --manifestdir
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:441:in `parse_options'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:340:in `block in run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:446:in `exit_on_fail'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:340:in `run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:128:in `run'
==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
==> default: /opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```

参考文献
github.com/mitchellh/vagrant/issues/3740

**Comment by mk2** [comment]
参考文献のissueから、下記のように書けば回避できるとわかった。

```ruby
  config.vm.provision "puppet", :options => ["--debug --trace --verbose"] do |puppet|
    puppet.environment      = 'develop'
    puppet.environment_path = 'manifests/environments'
  end
```
